import { Inter } from "next/font/google";
import "./globals.css"; // 
import Header from "./components/Header";
import { AuthContextProvider } from "@/context/authprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sitio Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <AuthContextProvider>
        <Header>
    
        </Header>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
